apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gpu-quota
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gpu-quota-user1
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: gpu-quota
                  namespace: user1
                spec:
                  hard:
                    requests.nvidia.com/gpu: "1"
                    limits.nvidia.com/gpu: "1"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gpu-quota-user2
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: gpu-quota
                  namespace: user2
                spec:
                  hard:
                    requests.nvidia.com/gpu: "1"
                    limits.nvidia.com/gpu: "1"
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-gpu-quota-placement
  namespace: default
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - rhoai
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-gpu-quota-placement
  namespace: default
placementRef:
  name: policy-gpu-quota-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-gpu-quota
    apiGroup: policy.open-cluster-management.io
    kind: Policy

