apiVersion: v1
kind: Pod
metadata:
  name: gpu-vram-load
  namespace: user1
spec:
  restartPolicy: Always
  containers:
  - name: cuda-nbody
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    # -benchmark: No window needed
    # -numbodies: This is the lever for VRAM. Higher = more memory used.
    args: ["-benchmark", "-numbodies=1024000"]
    resources:
      limits:
        nvidia.com/gpu: 1
