apiVersion: v1
kind: Pod
metadata:
  name: gpu-load-user1
  namespace: user1-namespace
spec:
  # This ensures the pod keeps running the test over and over
  restartPolicy: Always
  containers:
  - name: cuda-nbody
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    # This specifically triggers the 'math-only' mode so it doesn't look for a screen
    args: ["-benchmark", "-numbodies=256000"]
    resources:
      limits:
        nvidia.com/gpu: 1
