apiVersion: v1
kind: Pod
metadata:
  name: gpu-vram-user1
  namespace: user1-namespace
spec:
  restartPolicy: Always
  containers:
  - name: cuda-nbody
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    # -numbodies=1024000: This uses significantly more VRAM
    args: ["-benchmark", "-numbodies=1024000"]
    resources:
      limits:
        nvidia.com/gpu: 1
