---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
  namespace: usera
spec:
  hard:
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-quota
  namespace: userb
spec:
  hard:
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
